<?php

namespace acem\ThreadBundle\Repository;

/**
 * ChannelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelsRepository extends \Doctrine\ORM\EntityRepository
{
}
