<?php

namespace acem\ThreadBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by thread Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
